const Constants = {
    DEFAULT_BLUE: '#255075',
    LIGHTER_BLUE: '#4A82B2',
    EVEN_LIGHTER_BLUE: '#6A9ECB',
    POPUP_TIMING_MSEC: 1500,
    MAX_NAME_LENGTH: 30,
    MAX_DESCRIPTION_LENGTH: 100,
    ACCESS_KEY: '@restaurants',
    RESULTS_PER_PAGE: 10,
    RANDOMIZER_DURATION_IN_MSEC: 1000,
    RANDOMIZER_INTERVAL_IN_MSEC: 100,
    ASCENDING: "ascending",
    DESCENDING: "descending",
}

export default Constants;